// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.polito.ai.gas.business;

import it.polito.ai.gas.business.MessagePK;
import java.io.Serializable;

privileged aspect MessagePK_Roo_Serializable {
    
    declare parents: MessagePK implements Serializable;
    
    private static final long MessagePK.serialVersionUID = 1L;
    
}
