// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.polito.ai.gas.business;

import it.polito.ai.gas.business.Producer;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Producer_Roo_Jpa_Entity {
    
    declare @type: Producer: @Entity;
    
    declare @type: Producer: @Table(name = "producer");
    
}
