// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.polito.ai.gas.business;

import it.polito.ai.gas.business.User;
import it.polito.ai.gas.business.UserType;

privileged aspect User_Roo_JavaBean {
    
    public UserType User.getRole() {
        return this.role;
    }
    
    public void User.setRole(UserType role) {
        this.role = role;
    }
    
}
