// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.polito.ai.gas.business;

import it.polito.ai.gas.business.PurchaseRequestDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseRequestDataOnDemand_Roo_Configurable {
    
    declare @type: PurchaseRequestDataOnDemand: @Configurable;
    
}
